name = "carousel"
compatibility_date = "2024-08-16"

[env.production]
route = { pattern = "carousel.pages.dev", zone_name = "pages.dev" }

[[env.production.build]]
command = "npm run build"
cwd = "."
watch_dir = "src"